apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapplication
  labels:
    app: pythonapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: index.docker.io/davidrv17/pythonapp:11ba37b
        imagePullPolicy: Always
        env:
          - name: SSH_PASS
            valueFrom:
              secretKeyRef:
                name: ssh-key
                key: password
          - name: SSH_USER
            valueFrom:
              secretKeyRef:
                name: ssh-key
                key: user
          - name: SSH_IP
            valueFrom:
              secretKeyRef:
                name: ssh-key
                key: ip
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp
spec:
  selector:
    app: pythonapp
  ports:
  - name: pythonport
    protocol: TCP
    port: 5000
