apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapplication
  labels:
    app: pythonapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: index.docker.io/davidrv17/pythonapp:c41f2a3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp
spec:
  selector:
    app: pythonapp
  ports:
  - name: pythonport
    protocol: TCP
    port: 5000
